package com.example.vitalio_cis

object Routes {

    const val LOGIN = "login"
    const val DASHBOARD = "dashboard"
    const val OTP = "otp"
    const val VITALS = "vitals"
    const val FLUID = "fluid"
    const val SYMPTOMSTRACKER = "symptomsTracker"
    const val SYMPTOMS = "symptoms"
    const val MEDICINE = "medicine"
    const val DIET = "diet"
    const val INTERACTION = "interaction"
    const val APPOINTMENTS = "appointments"
    const val ARTICLES = "articles"
    const val MANAGE_MEDICINE = "manageMedicine"
    const val FINDDOCTOR = "findDoctor"
    const val DOCTORDETAILS = "doctorDetails"
    const val BOOKINGCONFERMATION = "bookingConfirmation"
    const val BOOKINGDETAILS = "bookingDetails"
    const val SELECTCLINIC = "selectClinic"
    const val DRAWER = "drawer"
    const val PERSONALIFSCREEN = "personalInfoScreen"
    const val LABREPORTS = "labReports"
    const val ALLERGIESSCREEN = "AllergiesScreen"
    const val ADDLABRESULTS = "AddLabResultsScreen"
    const val MANAGEMEDICAIONS  = "ManageMedicationsPreview"
    const val ADDMEDICINEREMINDER  = "AddMedicineReminderScreen"
    const val INTERACTIONCHECKER  = "InteractionCheckerScreen"
    const val DIETCHECKLIST  = "DietChecklistScreen"
    const val PRESCRIPTION  = "PrescriptionScreen"
    const val FLUIDDATAINPUT  = "FluidDataInputScreen"
    const val FLUIDOUTPUTHISTORY  = "FluidOutputHistoryScreen"
    const val FLUIDINPUTHISTORY  = "FluidInputHistoryScreen"
    const val VITALHISTORY  = "VitalHistoryScreen"
    const val CONNECTION  = "ConnectionScreen"
    const val ARTICALEDETAILS  = "ArticleDetailScreen"
    const val MYOBSERVERS  = "MyObserversScreen"
    const val FAMILYHEALTH  = "FamilyHealthScreen"
    const val ADDACTIVITY  = "AddActivityScreen"
    const val REMINDERS  = "RemindersScreen"
    const val EMERGENCYCONTACTS  = "EmergencyContactsScreen"
    const val CONNECTWATCH  = "ConnectWatchScreen"
    const val SHAREDACCOUNT  = "SharedAccountScreen"
    const val ADDMEMBER  = "AddMemberScreen"
    const val FAQ  = "FAQScreen"
    const val FEEDBACK  = "FeedbackScreen"
    const val MEDICALPROFILE  = "MedicalProfileScreen"
    const val RESEARCHARTICLES  = "ResearchArticlesScreen"

}